### ISSUE TITLE
Προσθήκη φίλτρων lua για τα μαθήματα του υποκεφαλαίου Περιεχόμενο Μαθημάτων της Ενότητας ΠΡΟΠΤΥΧΙΑΚΕΣ ΣΠΟΥΔΕΣ. 

### ISSUE THREAD

**Issue by nkanagno** [ioniodi/guide#4]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
   - Αλλαγή:
Προσθήκη φίλτρων `.lua` αρχείων που να παιρνουν ως παράμετρο το μάθημα σε μορφή `.md` που θα παίρνει από το [all_collections](https://github.com/ioniodi/all_collections/tree/master) και να εμφανίζει στο βιβλίο τον τίτλο (σε μορφή header 4 `####`) και το περιεχόμενό του, χωρισμένα στο txt ανά εξάμηνο στο υποκεφάλαιο Περιεχόμενο Μαθημάτων της Ενότητας ΠΡΟΠΤΥΧΙΑΚΕΣ ΣΠΟΥΔΕΣ. Τα 4 διαφορετικά φίλτρα θα χωρίζονται σε 4 κατηγορίες:
      - Κορμού
      - Επιλογής
      - Κατεύθυνσης Πληροφοριακών Συστημάτων
      - Κατεύθυνσης Πληροφορική - Ανθρωπιστικές και Κοινωνικές Επιστήμες
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Axileaszervos @inf2021090 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
  - [Επίσημος Οδηγός Σπουδών](https://di.ionio.gr/gr/students/student-prospectus/)
### DEMO LINK
Σύνδεσμος σε προσωπικό issue που περιέχει το [pdf βιβλίο demo](https://github.com/nkanagno/guide/issues/1)
### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

@epidrome

**Comment by epidrome** [comment]
@nkanagno αν θες βάλε ένα ενδεικτικό PDF σε ένα issue

**Comment by nkanagno** [comment]
@epidrome, Πραγματοποίησα τις απαραίτητες αλλαγές προσθέτοντας σύνδεσμο που οδηγεί σε προσωπικό issue όπου έχει ανεβεί το [pdf βιβλίο demo](https://github.com/nkanagno/guide/issues/1).
