### ISSUE TITLE
Δημιουργία και προσθηκή φίλτρων lua, για την εμφάνηση των καθηγητών του οδηγού σπουδών

### ISSUE THREAD

**Issue by Axileaszervos** [ioniodi/guide#5]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
  * Αλλαγή:
     Δημιουργία τεσσάρων φίλτρων `lua`, με σκοπό την εμφάνιση σε pdf του κεφαλαίου ΚΑΘΗΓΗΤΈΣ του οδηγού σπουδών. Πιο συγκεκρινένα, δημιούργησα τέσσερα φίλτρα, τα οποία χρησιμοποιούνται για την κατηγοροποίηση των καθηγητών, δηλαδή ένα φίλτρο άνα κατηγορία.

    * [AssiPro.lua](https://github.com/Axileaszervos/LUA-FILTERS---MAKE-LATEX/blob/main/AssiPro.lua)
    * [AssoPro.lua](https://github.com/Axileaszervos/LUA-FILTERS---MAKE-LATEX/blob/main/AssoPro.lua)
    * [Pro.lua](https://github.com/Axileaszervos/LUA-FILTERS---MAKE-LATEX/blob/main/Pro.lua)
    * [Medip.lua](https://github.com/Axileaszervos/LUA-FILTERS---MAKE-LATEX/blob/main/Medip.lua)
 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @nkanagno @inf2021090 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
  * Η επίσημη [ιστοσελίδα](https://di.ionio.gr/gr/department/staff/professors/) των μελών ΔΕΠ του τμήματος πληροφορικής του ιονίου πανεπιστημίου. 
  * Η επίσημη [ιστοσελίδα](https://di.ionio.gr/gr/department/staff/administrative-staff/) του Διοικητικού Προσωπικού του τμήματος πληροφορικής του ιονίου πανεπιστημίου.
  * Η ανεπίσημη [ιστοσελίδα](https://epic-hamilton-da9ac8.netlify.app/) του τμήματος πληροφορικής του ιονίου πανεπιστημίου.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

@epidrome

**Comment by epidrome** [comment]
@Axileaszervos αν θες βάλε ένα ενδεικτικό PDF σε ένα issue

**Comment by Axileaszervos** [comment]
[mypdf](https://github.com/Axileaszervos/iv/issues)
